### ISSUE TITLE
[Feature] 업체 검색 

### ISSUE THREAD

**Issue by DevLeeSeonwoo** [Hobak-Goguma/DaangnMarket-django#12]
## 맥락
원하는 키워드에 맞는 자신 근처의 업체를 검색하는 서비스
#
- 로직은 물품 검색이랑 동일

1. header에 id-member값으로 회원 비회원 구분
2. 멤버가 주소가 설정되어 있지 않을 시, 주소 등록 요청
3. 비회원은 전체 업체 검색
4. 주소가 등록된 회원은 그 주소와 설정된 거리값을 이용해 근처 업체를 조회한다

**Comment by ddusi** [comment]
Company models에서 category 필드 수정
