### ISSUE TITLE
[Feature] 카테고리 검색 비회원 회원 구분 

### ISSUE THREAD

**Issue by Paca2** [Hobak-Goguma/DaangnMarket-django#3]
카테고리 검색 시, 제품 검색과 같이 사용자가 설정한 거리에 따라 검색할지 
혹은 카테고리 검색 시 해당 카테고리에 대한 모든제품을 검색할 지 논의필요

**Comment by DevLeeSeonwoo** [comment]
동의합니다. 직거래를 유도하는 당근마켓 취지에도 맞는 것 같습니다
