### ISSUE TITLE
[Update] member_addr API  유효성검사, 파싱

### ISSUE THREAD

**Issue by ddusi** [Hobak-Goguma/DaangnMarket-django#8]
## 맥락

1. 각 member_addr 처리시 거리값을 view에서 유효성체크를 하고 있다. 이 것을 TextChoices이나, Form과 같은 기능들을 사용하여 좀더 django 스러운, 개발자스러운 코드로 변환하고 싶다. 
2. addr 설정은 결국 로그인이 선행되고나서 할 행동들이기 때문에 member_id를 보내는 것 보다는,  header값에서 파싱해오는게 맞지 않을까? 
3. addr 값을 쓰는곳에서(product/ company 같은 성격) 데이터를 넣을때도 유효성 검사를 해야함. ( 실제 db에서 사용할 수 있는 값인지 )
4. path 파람으로 id_member값을 받고있는데, body에서 id_member 또 받고있음. 

관련 파일들
- member_addr_views.py
- member_addr_models.py

**Comment by DevLeeSeonwoo** [comment]
1번 내용이랑 3번 내용의 차이가 뭐죠?

**Comment by ddusi** [comment]
1번은 distance에 대한 유효성 체크입니다. 
3번은 다른 업체 모델이나, product모델에서도 addr을 넣을때 유효성 체크를 뜻합니다.
